### ISSUE TITLE
Package name should be folder name

### ISSUE THREAD

**Issue by iamdejan** [sungindra/go-dummy-proj#2]
In Golang, it is best practice to use the folder name as package name.

E.g. in your project, you have file `modelController.go`. The package (see [here](https://github.com/sungindra/go-dummy-proj/blob/master/controller/api/modelController.go#L1)) should be `api` instead of `controller`.

**Comment by sungindra** [comment]
but package name in that particular file is `api` Mr @iamdejan

**Comment by iamdejan** [comment]
Whoops, sorry. I must have been drunk.
